name: Update RU IP List
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate MikroTik RSC
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Commit and Push
        run: |
          git config --global user.name "Gitea Action"
          git config --global user.email "action@noreply.gitea.io"
          git add ru.rsc
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update RU IP list [skip ci]"
            git push
          fi
